spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sf_prod?verifyServerCertificate=FALSE&useSSL=TRUE&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: sf_prod_user
    password: ic
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false